name: Dependency Lock File Check

on:
  pull_request:
    paths:
      - 'package.json'
  push:
    paths:
      - 'package.json'

jobs:
  check-lock-file:
    name: Verify Lock File
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Need history to check for changes
      
      - name: Check if package.json was modified
        id: check-package
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q "package.json"; then
            echo "modified=true" >> $GITHUB_OUTPUT
            echo "📦 package.json was modified"
          else
            echo "modified=false" >> $GITHUB_OUTPUT
            echo "✅ package.json was not modified"
          fi
      
      - name: Check if package-lock.json was updated
        if: steps.check-package.outputs.modified == 'true'
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q "package-lock.json"; then
            echo "✅ package-lock.json was also updated"
          else
            echo "❌ ERROR: package.json was modified but package-lock.json was not!"
            echo ""
            echo "Please run 'npm install' locally and commit the updated package-lock.json"
            echo ""
            echo "Steps to fix:"
            echo "1. git checkout ${{ github.head_ref || github.ref_name }}"
            echo "2. npm install"
            echo "3. git add package-lock.json"
            echo "4. git commit -m 'Update package-lock.json'"
            echo "5. git push"
            exit 1
          fi
      
      - name: Verify package-lock.json exists
        run: |
          if [ ! -f "package-lock.json" ]; then
            echo "❌ ERROR: package-lock.json not found!"
            echo ""
            echo "This file is required for CI/CD to work properly."
            echo ""
            echo "To fix:"
            echo "1. Run 'npm install' in your local repository"
            echo "2. Commit the generated package-lock.json file"
            echo "3. Push your changes"
            exit 1
          fi
          echo "✅ package-lock.json exists"
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      
      - name: Verify lock file integrity
        run: |
          echo "🔍 Verifying package-lock.json integrity..."
          npm ci --dry-run
          if [ $? -eq 0 ]; then
            echo "✅ package-lock.json is valid and in sync"
          else
            echo "❌ package-lock.json is corrupted or out of sync"
            echo ""
            echo "To fix:"
            echo "1. Delete package-lock.json"
            echo "2. Run 'npm install'"
            echo "3. Commit the new package-lock.json"
            echo "4. Push your changes"
            exit 1
          fi
      
      - name: Check for security vulnerabilities
        continue-on-error: true
        run: |
          echo "🔒 Checking for security vulnerabilities..."
          npm audit --production
          
          # Count high severity vulnerabilities
          HIGH_VULNS=$(npm audit --json --production | jq '.metadata.vulnerabilities.high // 0')
          CRITICAL_VULNS=$(npm audit --json --production | jq '.metadata.vulnerabilities.critical // 0')
          
          if [ "$CRITICAL_VULNS" -gt 0 ]; then
            echo "⚠️ WARNING: $CRITICAL_VULNS critical vulnerabilities found!"
            echo "Run 'npm audit fix' to attempt automatic fixes"
          elif [ "$HIGH_VULNS" -gt 0 ]; then
            echo "⚠️ WARNING: $HIGH_VULNS high severity vulnerabilities found!"
          else
            echo "✅ No high or critical vulnerabilities found"
          fi
      
      - name: Generate dependency report
        if: always()
        run: |
          echo "📊 Dependency Report"
          echo "===================="
          echo ""
          echo "Total dependencies: $(npm ls --depth=0 --json | jq '.dependencies | length')"
          echo "Dev dependencies: $(npm ls --depth=0 --json --dev | jq '.dependencies | length')"
          echo ""
          echo "Package versions:"
          npm ls --depth=0
      
      - name: Comment on PR
        if: failure() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const message = `## ❌ Dependency Check Failed
            
            The package-lock.json file needs to be updated to match package.json changes.
            
            ### Quick Fix:
            \`\`\`bash
            git checkout ${{ github.head_ref }}
            npm install
            git add package-lock.json
            git commit -m "Update package-lock.json"
            git push
            \`\`\`
            
            ### Why is this important?
            - Ensures reproducible builds
            - Prevents "Dependencies lock file not found" errors in CI
            - Maintains consistent dependency versions across environments
            
            Please update your branch and push again.`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            });