name: Tests

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]
  workflow_dispatch:

jobs:
  lint:
    name: Lint & Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run lint
      - name: Run TypeScript check
        run: npm run typecheck
      - name: Run Vue TypeScript check
        run: npm run check

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run unit tests (Vue components)
        run: npm run test
      - name: Run vanilla JS tests
        run: npm run test:vanilla
      - name: Generate coverage report
        run: npm run test:coverage
      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/
          retention-days: 14
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: ./coverage/
          fail_ci_if_error: false

  component-tests:
    name: Component Tests
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run component tests (UI components)
        run: npm run test -- --testNamePattern="components/ui"
      - name: Run integration tests (store interactions)
        run: npm run test -- --testNamePattern="integration"
      - name: Upload component test results
        uses: actions/upload-artifact@v3
        with:
          name: component-test-results
          path: test-results/html/
          if-no-files-found: ignore

  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    needs: component-tests
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - name: Set up test environment
        run: |
          mkdir -p data/db
          touch data/db/users.test.db
      - name: Start server
        run: |
          npm run dev &
          echo $! > server.pid
          sleep 10
      - name: Run E2E tests
        run: npm run test:e2e
      - name: Kill server
        if: always()
        run: kill $(cat server.pid) || true
      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: e2e-test-results/html/
          retention-days: 30
      - name: Upload Playwright test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-test-results
          path: e2e-test-results/
          retention-days: 30

  visual-tests:
    name: Visual Regression Tests
    runs-on: ubuntu-latest
    needs: component-tests
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - name: Start server
        run: |
          npm run dev &
          echo $! > server.pid
          sleep 10
      - name: Run visual tests
        run: npx playwright test --project=visual-regression
      - name: Kill server
        if: always()
        run: kill $(cat server.pid) || true
      - name: Upload screenshot diffs
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: visual-test-diffs
          path: e2e-test-results/artifacts
          retention-days: 30

  publish-test-results:
    name: Publish Test Results
    runs-on: ubuntu-latest
    needs: [unit-tests, component-tests, e2e-tests, visual-tests]
    if: always()
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts
      
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: artifacts/**/*.xml
          comment_mode: always
      
      - name: Notify on Slack
        uses: 8398a7/action-slack@v3
        if: always()
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}